name: Daily Portfolio Update

on:
  schedule:
    - cron: '0 4 * * *' # Runs every day at 6:00 UTC
  workflow_dispatch:

jobs:
  run-daily-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run daily price tracker
        run: python daily_price_tracker.py
      - name: Run portfolio recompiler
        run: python portfolio_recompiler.py
